# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sav_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('amount', models.IntegerField(default=0)),
                ('sav_type', models.CharField(max_length=10)),
                ('sav_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
