# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gold_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.IntegerField(default=0)),
                ('sell_price', models.IntegerField(default=0)),
                ('add_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
