# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanage', '0003_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('fixed', models.FloatField(default=0.0)),
                ('saving', models.FloatField(default=0.0)),
                ('add_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
