# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanage', '0005_auto_20170503_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='sav_list',
            name='owner',
            field=models.TextField(default=''),
        ),
    ]
